### ISSUE TITLE
Reference à des objets http dans des pages HTTPS

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#1]
Des appels HTTP dans des pages en HTTPS ce qui affiche une alerte dans le navigateur.

Message dans la console : 
> Chargement du contenu mixte d’affichage « http://mansonthomas.com/CRF/RedCrossQuest/preview.png » (non sécurisé) sur une page sécurisée[En savoir plus]
vendor-4a7aed3762.js:35124:8
> Chargement du contenu mixte d’affichage « http://mansonthomas.com/CRF/RedCrossQuest/protection_donnees_perso.mp4 » (non sécurisé) sur une page sécurisée[En savoir plus]

**Comment by dev-mansonthomas** [comment]
Fixed in this commit :
https://github.com/dev-mansonthomas/RedCrossQuest/commit/19c4de22bda9da3b2fcf454960a55974c6d49ed1#diff-a2232a4c82535933188bcaeaf8d2d5ce
