### ISSUE TITLE
Possibilité d'afficher les points de quête sur une carte

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#2]
Sur la page "/#!/pointsQuetes", en plus de la liste des points de quetes permettre d'afficher ceux-ci directement sur une carte. (visuel plus parlant qu'une liste pour retrouver rapidement un point de quête).
En utilisant le même type de visu que le graph qui permet de suivre le rendement des point de quêtes actif, mais pour simplement visualiser les points de quête déclarés. Avec un lien vers la page descriptive du point de quête en cliquant sur celui-ci sur la carte

**Comment by dev-mansonthomas** [comment]
Done, dans le graphique de l'opérateur
