### ISSUE TITLE
Lieu de quetes ne remonte pas dans la liste des queteurs filtré

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#3]
Sur la page /#!/queteurs,
 * Sans filtrage: le lieu prévisionnel de quête est affiché sur les quêteurs non partis (date théorique de départ affichée aussi)
 * en filtrant sur les quêteurs non partis : le lieu de quête n'est plus affiché. (date théorique de départ toujours affichée)

**Comment by dev-mansonthomas** [comment]
Fixed
