### ISSUE TITLE
[Site de test] URL d'inscription à redquest

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#35]
Sur le site de test, l'url d'inscription à redquest est non fonctionnelle => https://test.test.redque.st/registration?uuid=xxxxxxxxxxxxxxx

Ok en enlevant l'un des "test." de l'url.

Cf. https://github.com/dev-mansonthomas/RedCrossQuest/blob/3961772587d43a828aa884feea8c76153bdbeb69/client/src/app/admin/QRCode/redQuest/redQuest.controller.js#L46

**Comment by dev-mansonthomas** [comment]
Merci !

j'ai corrigé, c'était une erreur paramétrage
