### ISSUE TITLE
Menu administration tronqué à droite

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#36]
Sur un écran avec une résolution de 1366x768, le menu Administration dépasse sur la droite de l'écran. 
Non reproduit sur un écran de 1920x1080

(testé sur firefox et chrome)

**Comment by dev-mansonthomas** [comment]
![image](https://user-images.githubusercontent.com/5695269/57543156-254b1400-7386-11e9-8a91-8ef13bf1ef89.png)

quand je simule la taille de l'écran en redimenssionnant, je n'ai pas le phénomène.

**Comment by amdouence** [comment]
Il s'agit du menu déroulé qui dépasse. Pas le bouton.
Et en fait il y a une barre de défilement qui apparait bien en bas de page si on veut se déplacer sur la droite pour tout voir. Pas super ergonomique mais fait le boulot.
![Capture](https://user-images.githubusercontent.com/15091487/57547765-83b0cc00-735f-11e9-9db1-3fc8d42632d3.PNG)
