### ISSUE TITLE
Page queteur : afficher le nom du lieu de quete plutot que son ID

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#37]
Sur la page d'un quêteur, en bas dans la liste des tronc, afficher le nom du lieu de quête plutôt que son ID qui n'est pas parlant.
Je pense qu'il est possible de gagner de la place en largeur en affichant les dates au format jj/mm/aa hh:mm au lieu de aaaa-mm-jj hh:mm:ss (14x3 caractères vs 19x3)

**Comment by dev-mansonthomas** [comment]
Oui, je note, c'est juste que techniquement, c'était un peu compliqué l'année dernière pour le faire, mais je devrais pouvoir faire la modification pour cette année.
