### ISSUE TITLE
Liste des tronc disponibles pour une action

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#39]
Sur les pages suivantes, une liste des tronc-queteurs éligibles à l'action pourrait être affichée, en plus de la saisie par QR code ou manuelle : 
* Départ : affiche dans un tableau la liste de tous les tronc préparés, avec num du tronc, nom du queteur, lieu de quete prévu, horaire de départ prévu (et bonus, la date en rouge si départ prévu dans le passé)
* Retour : liste de tous les tronc déja partis, nom du queteur, lieu de quete, et en bonus la durée de quete => permet de s'inquieter si un queteur n'est pas rentré et de détécter une anomalie probable
* Comptage : liste des tronc revenus, nom du queteur, lieu de quete => permet de detecter si tous les tronc on bien été comptés et qu'il n'en manque pas un

**Comment by dev-mansonthomas** [comment]
Je vais y réfléchir.
les graphiques donnent ces informations (avec possibilité de cliquer sur un lien pour revenir sur l'application)

**Comment by dev-mansonthomas** [comment]
implémenté avec d7526288a20c9905839efac71758489c33b7a681
