### ISSUE TITLE
Préparation de tronc : saisie du lieu de quête avec proposition de choix

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#4]
Dans le formulaire de préparation d'un tronc, il serait pratique de permettre la saisir du texte pour remplir le lieu de quête et remonter une liste au fur et à mesure de la saisie correspondant aux résultats. (comme c'est le cas pour la saisie manuelle des troncs ou des quêteurs)
Permet une simplification de la recherche des points de quête lorsque la liste est longue.

**Comment by dev-mansonthomas** [comment]
Done
