### ISSUE TITLE
Page préparation : le message d'alerte pour un mineur est affichée par défaut

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#41]
Sur la page de préparation d'un tronc/quêteur, en arrivant sur la page le message "Attention! le quêteur est mineur et le point de quête n'autorise pas les mineurs." est affiché par défaut.
Il disparait bien lors de la saisie d'un queteur majeur.

**Comment by dev-mansonthomas** [comment]
Je pense avoir corriger le problème de moi meme dans l'interval.
Rouvre le ticket si tu revois un souci
