### ISSUE TITLE
Préparation du tronc : pas de message d'erreur à la saisie

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#42]
Lors de la préparation d'un tronc, si un champs requis dans le formulaire est absent la sauvegarde ne fonctionne pas (fonctionnement ok) et aucun message d'erreur ne s'affiche pour indiquer les champs à compléter.
Généralement, dans ce type de situation les champs maquant après validation sont indiqués en rouge.

**Comment by dev-mansonthomas** [comment]
ok, je vais regarder ca
