### ISSUE TITLE
Affichage de la chaine de caractère { Tronc-Quêteur }

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#43]
Est ce qu'il est volontaire que la chaine { Tronc-Quêteur } s'affiche ou est ce que c'est une balise de mise en forme type twig qui est mal interprété/remplie ?

**Comment by dev-mansonthomas** [comment]
Oui, c'est normal, c'est pour donner un style.

Il y a 3 notions distinctes : 
Le queteur
le tronc

et l'association tronc-queteur (quand on envoie qqn queter)
