### ISSUE TITLE
Page Login

### ISSUE THREAD

**Issue by amdouence** [dev-mansonthomas/RedCrossQuest#60]
Après avoir saisi login / mdp, en tapant sur la touche _entrer_ en lance la réinitialisation du mot de passe, plutot que la validation du formulaire.

**Comment by amdouence** [comment]
Visiblement pas systématique. Je vais essayer de qualifier plus précisément le comportement.

**Comment by dev-mansonthomas** [comment]
hello,
c'est marrant parce que j'utilise systématiquement la touche entrée et je n'ai jamais eu le souci.
t'avais pas fait un coup de "tab" avant qui ait pu fausser le truc ?
