### ISSUE TITLE
$ref values must be RFC3986-compliant percent-encoded URIs (Error)

### ISSUE THREAD

**Issue by Ethiraj89** [dev-mansonthomas/RedCrossQuest#79]
Hi Team,
     While enabling swagger in our API, we receiving an error like $ref values must be RFC3986-compliant percent-encoded URIs in swagger editor. When I cross verified this issue, Its pointing our user defined class which we have used for the concept of paged collection. Kindly give me the solution to resolve this issue.

Semantic error : get.responses.200.schema.$ref
$ref values must be RFC3986-compliant percent-encoded URIs

YAML:

get:
      tags:
        - channel
      operationId: 
      consumes: []
      produces:
        - application/json
        - text/json
      parameters:
        - name: Id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PagedCollection[Model]'
  '/api/{Id}/channel': (error)

**Comment by dev-mansonthomas** [comment]
Issue submitted to the wrong project
